# Based on https://github.com/tenacityteam/tenacity-flatpak-nightly
name: Flatpak

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  # App ID (reverse-DNS) (example= org.tenacityaudio.Tenacity)
  APP_ID: io.github.Mrmayman.QuantumLauncher
  # Path to manifest (example= org.tenacityaudio.Tenacity.yaml)
  MANIFEST_PATH: io.github.Mrmayman.QuantumLauncher.yml
  # Name of Docker image (example= tenacity)
  IMAGE_NAME: quantum-launcher
  # Tag of image  (example= stable, beta, nightly)
  IMAGE_TAG: stable
  # Name of bundle (excl. .flatpak) (example= tenacity)
  FLATPAK_BUNDLE: quantum-launcher
  # Flatpak branch (example= stable, beta, nightly)
  FLATPAK_BRANCH: stable

  FLATPAK_BUILD_DIR: build-dir
  FLATPAK_BUILD_REPO: build-repo

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Install flatpak-builder
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install flatpak-builder

    - name: Download flatpak SDK and sources
      run: |
        set -e
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak-builder --default-branch=${FLATPAK_BRANCH} --install-deps-from=flathub --install-deps-only --user /dev/null ${MANIFEST_PATH}
        flatpak-builder --default-branch=${FLATPAK_BRANCH} --download-only /dev/null ${MANIFEST_PATH}

    # In Ubuntu, Git no longer allows you to add a submodule via file:///
    # transport. As a fix, run git config --global protocol.file.allow always
    - name: Fix Git
      run: |
        git config --global protocol.file.allow always

    - name: Build flatpak
      run: |
        set -e
        flatpak-builder --default-branch=${FLATPAK_BRANCH} --disable-updates --disable-download --ccache --sandbox --repo=${FLATPAK_BUILD_REPO}-${{ matrix.arch }} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}

    - name: Upload flatpak repo
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.FLATPAK_BUILD_REPO }}-${{ matrix.arch }}
        path: ${{ env.FLATPAK_BUILD_REPO }}-${{ matrix.arch }}

  publish-oci:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs: build

    steps:
    - name: Install flatpak and libcontainers tools
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install skopeo flatpak jq podman

    - name: Download flatpak repo
      uses: actions/download-artifact@v6
      with:
        pattern: ${{ env.FLATPAK_BUILD_REPO }}-*

    - name: Create and Publish OCI bundles
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        REGISTRY_AUTH_FILE: /tmp/auth.json
      run: |
        export IMAGE_REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
        set -e
        echo "$GITHUB_TOKEN" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
        podman manifest create local-list

        for ARCH in amd64 arm64; do
          if [ "$ARCH" == "amd64" ]; then FLATPAK_ARCH="x86_64"; else FLATPAK_ARCH="aarch64"; fi
          REPO_DIR="${FLATPAK_BUILD_REPO}-${ARCH}"
          BUNDLE_NAME="${FLATPAK_BUNDLE}-${ARCH}"
          echo "Building bundle for $ARCH ($FLATPAK_ARCH)..."
          mkdir -p ${REPO_DIR}/{extensions,refs/{mirrors,remotes},state,tmp/cache}
          flatpak build-bundle \
            --arch=${FLATPAK_ARCH} \
            --oci \
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
            ${REPO_DIR} ${BUNDLE_NAME} ${APP_ID} ${FLATPAK_BRANCH}

          podman manifest add --arch $ARCH local-list oci:${BUNDLE_NAME}
        done

        podman manifest push --all local-list docker://ghcr.io/${IMAGE_REPOSITORY}:${IMAGE_TAG}

    - name: Update static index
      env:
        REGISTRY_AUTH_FILE: /tmp/auth.json
      run: |
        export IMAGE_REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
        set -e
        git clone -b gh-pages https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git gh-pages

        AMD64_JSON=$(skopeo inspect --override-os=linux --override-arch=amd64 docker://ghcr.io/${IMAGE_REPOSITORY}:$IMAGE_TAG)
        ARM64_JSON=$(skopeo inspect --override-os=linux --override-arch=arm64 docker://ghcr.io/${IMAGE_REPOSITORY}:$IMAGE_TAG)
        jq -n --argjson amd64 "$AMD64_JSON" --argjson arm64 "$ARM64_JSON" \
          '{ "Registry": "https://ghcr.io/", "Results": [ { "Name": "'${IMAGE_REPOSITORY}'", "Images": [$amd64, $arm64] } ] }' \
          > gh-pages/index/static
        cd gh-pages
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add index/static
        git commit -m "Update index for ${GITHUB_SHA:0:7}"
        git push
